#!/bin/bash

set -ex
export LC_ALL=C

dir=$(pwd)

# build SDF library
mkdir $dir/SDF
wget -q -O $dir/SDF/C.tar.gz "https://github.com/epochpic/SDF_C/archive/refs/tags/v14.4.10.tar.gz" 
mkdir $dir/SDF/C
tar -C $dir/SDF/C --strip-components=1 -xzf $dir/SDF/C.tar.gz
rm -f $dir/SDF/C.tar.gz
cd $dir/SDF/C ; make
wget -q -O $dir/SDF/utilities.tar.gz "https://github.com/epochpic/SDF_utilities/archive/refs/tags/v2.6.15.tar.gz"
mkdir $dir/SDF/utilities
tar -C $dir/SDF/utilities --strip-components=1 -xzf $dir/SDF/utilities.tar.gz
rm -f $dir/SDF/utilities.tar.gz
cd $dir/SDF/utilities ; ./build.sh
rm -rf $dir/SDF

# copy data
cd $dir
wget -q -O data.zip "https://zenodo.org/record/5711101/files/data.zip?download=1" 
unzip data.zip
rm -f $dir/data.zip
