#!/bin/bash

set -ex
export LC_ALL=C

#sudo apt-get install unzip

dir=$(pwd)

# build SDF library
mkdir $dir/SDF
git clone https://github.com/keithbennett/SDF_C.git $dir/SDF/C
cd $dir/SDF/C ; make 
git clone https://github.com/keithbennett/SDF_utilities.git $dir/SDF/utilities
cd $dir/SDF/utilities ; ./build
rm -rf $dir/SDF

# copy data
wget -O $dir/data.zip "https://zenodo.org/record/5711101/files/data.zip?download=1"

# obtain 7zip
#wget -O $dir/7z.tar.xz https://github.com/ip7z/7zip/releases/download/25.01/7z2501-linux-x64.tar.xz
#mkdir $dir/7z
#tar -xvf $dir/7z.tar.xz -C $dir/7z 

# uncompress data
#$dir/7z/7zz x $dir/data.zip "-o$dir"

unzip $dir/data.zip -d $dir

# clean
rm -rf $dir/SDF $dir/7z.tar.xz $dir/7z $dir/data.zip
